"""
Created on Sun Nov 24 19:34

Author: Márcia Jacobina Andrade Martins
Instituto de Computação - IC
Universidade Estadual de Campinas - UNICAMP
E-mail: m905106@dac.unicamp.br

"""

# Import the translation of active ingredients generated by the META model 
# for later comparison with DrugBank data. This process supports the evaluation 
# of translation quality and consistency for active ingredient names in English.

import csv

def import_translated_active_ingredients_meta(cnx, cursor):
    # Load the file containing active ingredients translated by the META model
    
    try:
        file_translation = "C:/project/healdb/data/output/output_active_ing_translate_meta.csv"

        # Clear the working table in the database before importing new data
        try:
            command_sql = "TRUNCATE TABLE healdb.hd_wrk_translate_eng_active_ing_meta;"
            cursor.execute(command_sql)
        except Exception as e:
            print(f"Error truncating the table `hd_wrk_translate_eng_active_ing_meta`: {e}")
            return

        print('Starting the import process...')

        # Open the CSV file and read the data
        try:
            with open(file_translation, "r", encoding="utf-8") as file:
                csv_reader = csv.reader(file, delimiter=',')
                next(csv_reader)  # Skip the header row

                # Process each row in the CSV file
                for row in csv_reader:
                    try:
                        # Extract the ID and translation from the row
                        id = row[0]
                        translation = row[2]
                        
                        # Create a record with the corresponding columns
                        register = (id, translation)
                        print(f"Processing record: {register}")

                        # Build the SQL insert command
                        command_sql = (
                            "INSERT INTO healdb.hd_wrk_translate_eng_active_ing_meta " 
                            "(id_active_ingredient, nm_active_ingredient_eng) "
                            "VALUES (%s, %s)"
                        )

                        # Execute the SQL command
                        cursor.execute(command_sql, register)
                    except Exception as e:
                        print(f"Error inserting record {register}: {e}")
                        continue

            # Commit the changes to the database
            cnx.commit()
            print("Import process completed successfully.")
        except FileNotFoundError:
            print(f"File not found: {file_translation}")
        except Exception as e:
            print(f"Error reading the file: {e}")

    except Exception as e:
        print(f"Error during the import process: {e}")

    return
